apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-postgres
  labels:
    app: lb-postgres
spec:
  selector:
    matchLabels:
      app: lb-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: lb-postgres
    spec:
      imagePullSecrets:
        - name: lb-postgres-secret
      securityContext:
        runAsUser: 1001
        fsGroup: 0
      initContainers:
        - name: init-pgdata
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/lib/postgresql/data/pgdata && chown -R 1001:0 /var/lib/postgresql/data']
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
      containers:
      - name: lb-postgres
        image: docker.io/fastcomply/lb-postgresql:13-debian-11-hll
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/bash", "-c"]
        args:
          - |
            if [ ! -s "$PGDATA/PG_VERSION" ]; then
              echo "Initializing database at $PGDATA"
              initdb -D "$PGDATA"
            fi
            exec postgres -c shared_preload_libraries=pgaudit -c pgaudit.log=all -c log_statement=all
        envFrom:
          - secretRef:
              name: lb-postgres-secret
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: lb-postgres
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3
          tcpSocket:
            port: 5432
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3
          tcpSocket:
            port: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
          subPath: pgdata
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: lb-postgres-data

