kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lb-postgres-data
spec:
  storageClassName: default # Change storage class as per k8s cluster.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
