apiVersion: v1
kind: Service
metadata:
  labels:
    app: lb-postgres
  name: lb-postgres-svc
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: lb-postgres
  type: ClusterIP
