[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = 0OIpPw2XTp+eHhmgqqdBbRVejX3HxF7Y1XitH+lkLV4=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens5 -j MASQUERADE; iptables -A INPUT -i wg0 -p tcp --dport 6443 -j ACCEPT; sudo iptables -A INPUT -p tcp --dport 31502 -j ACCEPT; sudo iptables -A INPUT -p tcp --dport 30554 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens5 -j MASQUERADE; iptables -D INPUT -i wg0 -p tcp --dport 6443 -j ACCEPT; sudo iptables -D INPUT -p tcp --dport 31502 -j ACCEPT; sudo iptables -D DINPUT -p tcp --dport 30554 -j ACCEPT
MTU = 1400

# Client 1
[Peer]
PublicKey = s269X5hb8UTRVgzsPhigDDySpnpFPoJqtEZIvx0almg=
AllowedIPs = 10.8.0.2/32
PersistentKeepalive = 25

# Client 2
[Peer]
PublicKey = ImBSqRIctnsA3UPlo4/FuWAp0Cqwl8mfNfhmf28/BBc=
AllowedIPs = 10.8.0.3/32
PersistentKeepalive = 25

# Client 3
[Peer]
PublicKey = 0o/YebWu2ecnZjINXCN5Z2OdPxwazLvG1g2Qx6PjT3I=
AllowedIPs = 10.8.0.4/32
PersistentKeepalive = 25

# Client 4
[Peer]
PublicKey = CCp1AHVZErqPKA4HkyLzQr8UJktR4RhPSQ5KeyGsP0Q=
AllowedIPs = 10.8.0.5/32
PersistentKeepalive = 25

# Client 5
[Peer]
PublicKey = OAcpURAPBwxmGFx177dzCpR5/p5cBv8ZNWiNsV7uvFI=
AllowedIPs = 10.8.0.6/32
PersistentKeepalive = 25

# Client 6
[Peer]
PublicKey = hOgw4RSwUDbx0oCFFIwTxEeZ053pLOCjJpnokFMVf0E=
AllowedIPs = 10.8.0.7/32
PersistentKeepalive = 25

# Client 7
[Peer]
PublicKey = a580AWUOgKXJfvZw1BsQeBOCDQchK2AnRIypSCbn5lQ=
AllowedIPs = 10.8.0.8/32
PersistentKeepalive = 25

# Client 8
[Peer]
PublicKey = VUWCh18lQKuw6qozn2ZCbc/3rQG6rprqFTfWzwH2C3Y=
AllowedIPs = 10.8.0.9/32
PersistentKeepalive = 25

# Client 9
[Peer]
PublicKey = a3hkIrwwhPWWoHPMVaio3i6pXQdIwgLABEPv0WssKg8=
AllowedIPs = 10.8.0.10/32
PersistentKeepalive = 25

# Client 10
[Peer]
PublicKey = fmtx8r7C+cAIbIpTsCPm7w81Kj2HNhhGLQfJXhv1DhQ=
AllowedIPs = 10.8.0.11/32
PersistentKeepalive = 25

# Client 11
[Peer]
PublicKey = 5l5SOeMp3DpZr/VDQauhtM27A1+GbHCov2icN2RX2Xk=
AllowedIPs = 10.8.0.12/32
PersistentKeepalive = 25

# Client 12
[Peer]
PublicKey = r4q2fZbvmizn8K2ScGD/zXMyNlRjuL79ELQGHHb3ZHQ=
AllowedIPs = 10.8.0.13/32
PersistentKeepalive = 25

# Client 13
[Peer]
PublicKey = /Bu13tzUbj2dEA0eIpPTl0WxZr8krxmcgBeX5cwTik0=
AllowedIPs = 10.8.0.14/32
PersistentKeepalive = 25

# Client 14
[Peer]
PublicKey = n54hRbORR2foDS8TAG7VFPlTmM43eARWTz5f6n8DWHA=
AllowedIPs = 10.8.0.15/32
PersistentKeepalive = 25

# Client 15
[Peer]
PublicKey = tl9WFOIOPp3px14gw9OReZ+oxLy2jBmgJrZyH4S04lw=
AllowedIPs = 10.8.0.16/32
PersistentKeepalive = 25

# Client 16
[Peer]
PublicKey = vdD4y/Fsf4rBiGCgR/ULGa0oPFYGMkUPsYZc+K5Mc20=
AllowedIPs = 10.8.0.17/32
PersistentKeepalive = 25

# Client 17
[Peer]
PublicKey = nkYBMPqs5rNGWJnDT5QCRUdIZpk/ygQkV/LUjUA5ogE=
AllowedIPs = 10.8.0.18/32
PersistentKeepalive = 25

# Client 18
[Peer]
PublicKey = pJjMQQHf12JDrLIDW4icJ4kOOM9UI7tmrvXo2bZG9nQ=
AllowedIPs = 10.8.0.19/32
PersistentKeepalive = 25

# Client 19
[Peer]
PublicKey = jqQScyA/hR4VMDJQ2r66WVEZc2fGbmNyQc7DK52N7QE=
AllowedIPs = 10.8.0.20/32
PersistentKeepalive = 25

# Client 20
[Peer]
PublicKey = 0P720cKO8WBguSThZXgjztbdpzUjzTiCg2Vi6ZjQvm8=
AllowedIPs = 10.8.0.21/32
PersistentKeepalive = 25

# Client 21
[Peer]
PublicKey = E4l7NVozuECBK5hPJje/UgZ4Ek7J2t8vMw4R8RC/+W0=
AllowedIPs = 10.8.0.22/32
PersistentKeepalive = 25