SELECT
   RTRIM(C.TABSCHEMA) AS SCHEMA_NAME,
   C.TABNAME AS TABLE_NAME,
   COALESCE(T.REMARKS, '') AS TABLE_DESCRIPTION,
   C.COLNAME AS COLUMN_NAME,
   C.TYPENAME DATA_TYPE,
   COALESCE(C.REMARKS, '') AS COLUMN_DESCRIPTION,
   CURRENT SERVER AS "database",
   FALSE AS IS_VIEW,
   T.CARD AS NUM_ROWS,
   CASE
       WHEN C.NULLS = 'Y' THEN TRUE
       WHEN C.NULLS = 'N' THEN FALSE
       ELSE NULL
   END AS IS_NULLABLE,
   CASE
       WHEN EXISTS (
           SELECT 1
           FROM SYSCAT.KEYCOLUSE K
           JOIN SYSCAT.TABCONST TC
             ON K.CONSTNAME = TC.CONSTNAME AND K.TABSCHEMA = TC.TABSCHEMA
           WHERE TC.TYPE = 'P'
             AND K.TABSCHEMA = C.TABSCHEMA
             AND K.TABNAME = C.TABNAME
             AND K.COLNAME = C.COLNAME
       ) THEN 'PRIMARY KEY'
       ELSE NULL
   END AS CONSTRAINT_TYPE,
   CASE
       WHEN T.NPAGES = -1 THEN -1
       ELSE T.NPAGES * 4096.0
   END AS TABLE_SIZE
FROM SYSCAT.COLUMNS C
JOIN SYSCAT.TABLES T
   ON C.TABNAME = T.TABNAME AND C.TABSCHEMA = T.TABSCHEMA
WHERE
   T.TYPE = 'T'
   AND C.TABSCHEMA NOT LIKE 'SYS%'
ORDER BY
   C.TABSCHEMA, C.TABNAME, C.COLNAME;
