SELECT
	T.TABLE_SCHEMA,
	COUNT(DISTINCT T.TABLE_NAME) AS TABLE_COUNT,
	COUNT(c.COLUMN_NAME) AS COLUMN_COUNT
FROM
    SYSIBM.TABLES T
JOIN
    SYSIBM.COLUMNS C
    ON T.TABLE_NAME = C.TABLE_NAME
    AND T.TABLE_SCHEMA = C.TABLE_SCHEMA
WHERE
	T.TABLE_SCHEMA NOT LIKE 'SYS%'
GROUP BY
	T.TABLE_SCHEMA;