SELECT
    SCHEMA_NAME,
    ROUND(SUM(TABLE_SIZE) / (1024 * 1024), 2) AS DATABASE_SIZE_MB
FROM
    M_TABLES
WHERE
    SCHEMA_NAME NOT LIKE 'SYS%'
    AND SCHEMA_NAME NOT LIKE '_SYS%'
GROUP BY
    SCHEMA_NAME;