SELECT
    t.SCHEMA_NAME,
    COUNT(DISTINCT t.TABLE_NAME) AS TABLE_COUNT,
    COUNT(c.COLUMN_NAME) AS COLUMN_COUNT
FROM
    M_TABLES t
JOIN
    SYS.TABLE_COLUMNS c
    ON t.TABLE_NAME = c.TABLE_NAME
    AND t.SCHEMA_NAME = c.SCHEMA_NAME
WHERE
    t.SCHEMA_NAME NOT LIKE 'SYS%' AND t.SCHEMA_NAME NOT LIKE '_SYS%'
GROUP BY
    t.SCHEMA_NAME;