apiVersion: v1
kind: Service
metadata:
  labels:
    app: lb-mysql
  name: lb-mysql-svc
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: lb-mysql
  type: ClusterIP